ContestMeter.Web.Site/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using ContestMeter.Web.Site.Database;
using ContestMeter.Web.Site.Database.Entities;
using ContestMeter.Web.Site.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ContestMeter.Web.Site.Controllers
{
    [Authorize(Roles = "administrator")]
    public class TeamController : Controller
    {
        private readonly ContestMeterDbContext _db = new ContestMeterDbContext();

        [AllowAnonymous]
        public ActionResult Index()
        {
            var model = new TeamsIndexViewModel
            {
                Teams = _db.Teams.Include(c => c.Contests).Include(p => p.Participants).ToList()
            };

            return View(model);
        }

        public ActionResult Create()
        {
            if (!User.IsInRole("administrator"))
            {
                TempData["Message"] = "Только администратор имеет право создавать команды";
                return RedirectToAction("Index");
                //ViewBag.ErrorMessage = "Только администратор имеет право создавать команды";
                //return View("Error");
            }
            var model = new TeamsCreateViewModel
            {
                Name = "",
                MaxTeamNumber = 1
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TeamsCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await _db.Teams.AnyAsync(c => c.Name == model.Name) || model.Name == "")
                {
                    ModelState.AddModelError("", "Команда с таким названием уже существует или не задано название команды");
                }
                else
                {
                    var team = new Team
                    {
                        Id = Guid.NewGuid(),
                        Name = model.Name,
                        MaxTeamNumber = model.MaxTeamNumber,
                        Rating = 0,
                        Contests = new HashSet<Contest>(),
                        Participants = new List<ApplicationUser>()
                    };

                    _db.Teams.Add(team);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var team = await _db.Teams.FindAsync(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            if (!User.IsInRole("administrator"))
            {
                TempData["Message"] = "Вы не имеете право редактировать эту команду";
                return RedirectToAction("Edit", new {id});
                //ViewBag.ErrorMessage = "Вы не имеете право редактировать эту команду";
                //return View("Error");
            }
            var model = new TeamsEditViewModel
            {
                TeamId = team.Id,
                Name = team.Name,
                MaxTeamNumber = team.MaxTeamNumber 
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(TeamsEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var currentTeam = _db.Teams.Find(model.TeamId);
                if (currentTeam == null)
                {
                    return HttpNotFound();
                }
                if ((await _db.Teams.AnyAsync(t => t.Name == model.Name) || model.Name == "") && model.MaxTeamNumber == currentTeam.MaxTeamNumber)
                {
                    ModelState.AddModelError("", "Команда с таким названием уже существует или не задано название команды");
                }
                else if (model.Name != "Одиночки" && currentTeam.Name == "Одиночки")
                {
                    ModelState.AddModelError("", "Нельзя изменить название у команды 'Одиночки'");
                }
                else
                {
                    if (model.MaxTeamNumber < currentTeam.Participants.Count)
                    {
                        ModelState.AddModelError("", "Максимальное количество участников в команде меньше, чем текущее количество участников. Пожалуйста, сначала сократите текущее количество участников в команде.");
                    }
                    else
                    {
                        var team = _db.Teams.Find(model.TeamId);
                        if (team == null)
                        {
                            return HttpNotFound();
                        }
                        team.Name = model.Name;
                        team.MaxTeamNumber = model.MaxTeamNumber;

                        _db.Entry(team).State = EntityState.Modified;
                        await _db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var team = await _db.Teams.FindAsync(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            if (!User.IsInRole("administrator"))
            {
                TempData["Message"] = "Только администратор имеет право удалять команды";
                return RedirectToAction("Edit", new { id });
                //ViewBag.ErrorMessage = "Только администратор имеет право удалять команды";
                //return View("Error");
            }
            return View(team);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            var team = await _db.Teams.FindAsync(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            var teamParticipants = _db.Users.Where(u => u.TeamId == id);
            foreach (var teamParticipant in teamParticipants)
            {
                teamParticipant.TeamId = null;
                teamParticipant.Team = null;
                _db.Entry(teamParticipant).State = EntityState.Modified;
            }

            _db.Teams.Remove(team);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        #region Contests
        public ActionResult TeamContestsList(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var team = _db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            if (!User.IsInRole("administrator"))
            {
                TempData["Message"] = "Только администратор имеет право просматривать список контестов для этой команды";
                return RedirectToAction("Edit", new { id });
                //ViewBag.ErrorMessage = "Только администратор имеет право просматривать список контестов для этой команды";
                //return View("Error");
            }
            var contests = _db.Contests;

            var teamContests = _db.TeamContests.Where(tc => tc.TeamId == team.Id).ToList();
            var contestIds = new List<Guid>();
            var teamContestIds = new List<Guid>();
            foreach (var contest in contests)
            {
                if (!teamContests.Any(tc => tc.TeamId == team.Id && tc.ContestId == contest.Id))
                    contestIds.Add(contest.Id);
                else
                    teamContestIds.Add(contest.Id);
            }

            var model = new TeamsContestsListViewModel
            {
                TeamId = id,
                Contests = _db.Contests.Include(c => c.Teacher).Include(c => c.ContestsType).Where(c => contestIds.Contains(c.Id)).AsQueryable(),
                TeamContests = _db.Contests.Include(c => c.Teacher).Include(c => c.ContestsType).Where(tc => teamContestIds.Contains(tc.Id)).AsQueryable()
            };

            return PartialView(model);
        }

        public async Task<ActionResult> AddContests(Guid? teamId, Guid? id)
        {
            if (teamId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var team = await _db.Teams.FindAsync(teamId);
            if (team == null)
            {
                return HttpNotFound();
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var teamContest = new TeamContest
            {
                Id = Guid.NewGuid(),
                TeamId = (Guid)teamId,
                ContestId = (Guid)id
            };

            var contest = _db.Contests.Find(id);
            if (contest == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            team.Contests.Add(contest);
            
            _db.Entry(teamContest).State = EntityState.Added;
            _db.Entry(team).State = EntityState.Modified;
            await _db.SaveChangesAsync();

            return RedirectToAction("Edit", new { id = teamId });
        }

        public async Task<ActionResult> DeleteContests(Guid? teamId, Guid? id)
        {

ContestMeter.Web.Site/Views/Shared/PartialError.cshtml
<h3 class="col-md-12">@ViewBag.ErrorMessage</h3>

ContestMeter.Web.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="@Url.Content("~/favicon.ico")" />
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" />
    <title>@ViewBag.Title - ContestMeter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    @*<span class="icon-bar"></span>*@
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("ContestMeter", "Index", "Home", null, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя", "Index", "Home")</li>
                    <li>@Html.ActionLink("О системе", "About", "Home")</li>
                    @*<li>@Html.ActionLink("Контакты", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @if (Request.IsAuthenticated)
    {
        <aside class="col-md-3" style="margin-top: 20px; text-align: center">@Html.Partial("_LeftSidebarPartial")</aside>
        <section class="col-md-9">
            <div class="body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; 2014-@DateTime.Now.Year - ContestMeter</p>
                </footer>
            </div>
        </section>
    }
    else
    {
        <section class="col-md-12">
            <div class="body-content">
                @RenderBody()
                <hr />
                <footer>
                    @if (DateTime.Now.Year >= 2014)
                    {
                        <p>&copy; 2014-@DateTime.Now.Year - ContestMeter</p>
                    }
                    else
                    {
                        <p>&copy; 2014-2015 - ContestMeter</p>
                    }
                </footer>
            </div>
        </section>
    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ContestMeter.Web.Site/Views/Shared/_LeftSidebarPartial.cshtml
@if (User.IsInRole("administrator"))
{
    <ul class="list-group nav">
        <li class="list-group-item">@Html.ActionLink("Контесты", "Index", "Contests")</li>
        <li class="list-group-item">@Html.ActionLink("Команды", "Index", "Team")</li>
        <li class="list-group-item">@Html.ActionLink("Администрирование", "Main", "Administrator")</li>
        <li class="list-group-item">@Html.ActionLink("Регистрация/удаление аккаунтов", "DeletedAccountsList", "Administrator")</li>
        <li class="list-group-item">@Html.ActionLink("Новости", "News", "Administrator")</li>
    </ul>
}
else if (User.IsInRole("teacher"))
{
    <ul class="list-group nav">
        <li class="list-group-item">@Html.ActionLink("Контесты", "Index", "Contests")</li>
        <li class="list-group-item">@Html.ActionLink("Команды", "Index", "Team")</li>
        @*<li class="list-group-item"><a href="/">Действие учителя 2</a></li>
        <li class="list-group-item"><a href="/">Действие учителя 3</a></li>
        <li class="list-group-item"><a href="/">Действие учителя 4</a></li>*@
    </ul>
}
else if (User.IsInRole("participant"))
{
    <ul class="list-group nav">
        <li class="list-group-item">@Html.ActionLink("Контесты", "Contests", "Participant")</li>
        <li class="list-group-item">@Html.ActionLink("Команды", "Index", "Team")</li>
        @*<li class="list-group-item"><a href="/">Действие участника 2</a></li>
        <li class="list-group-item"><a href="/">Действие участника 3</a></li>
        <li class="list-group-item"><a href="/">Действие участника 4</a></li>*@
    </ul>
}