ContestMeter.Web.Site/Models/ContestsViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using ContestMeter.Web.Site.Database.Entities;

namespace ContestMeter.Web.Site.Models
{
    public class ContestsIndexViewModel
    {
        public IEnumerable<Contest> Contests { get; set; }
    }

    public class ContestsCreateViewModel
    {
        public SelectList ContestsTypes { get; set; }

        [Required(ErrorMessage = "Необходимо выбрать тип контеста")]
        [Display(Name = "Тип контеста")]
        public Guid ContestsTypeId { get; set; }

        [Required(ErrorMessage = "Необходимо выбрать название контеста")]
        [MaxLength(150, ErrorMessage = "{0} не должно превышать {1} символов")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Активный?")]
        public bool IsActive { get; set; }
    }

    public class ContestsEditViewModel
    {
        public SelectList ContestsTypes { get; set; }

        public Guid ContestId { get; set; }

        public string TeacherId { get; set; }

        [Required(ErrorMessage = "Необходимо выбрать тип контеста")]
        [Display(Name = "Тип контеста")]
        public Guid ContestsTypeId { get; set; }

        [Required(ErrorMessage = "Необходимо выбрать название контеста")]
        [MaxLength(150, ErrorMessage = "{0} не должно превышать {1} символов")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Активный?")]
        public bool IsActive { get; set; }
    }

    public class ContestsExceptionsLogsViewModel
    {
        public IQueryable<ExceptionsLog> ExceptionsLogs { get; set; }

        public string ContestName { get; set; }
    }
}

ContestMeter.Web.Site/Controllers/ContestsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using ContestMeter.Web.Site.Database.Entities;
using ContestMeter.Web.Site.Database;
using ContestMeter.Web.Site.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ContestMeter.Web.Site.Controllers
{
    [Authorize(Roles = "administrator, teacher")]
    public class ContestsController : Controller
    {
        private ContestMeterDbContext _db = new ContestMeterDbContext();

        public async System.Threading.Tasks.Task<ActionResult> Index()
        {
            ContestsIndexViewModel model;
            if (!User.IsInRole("administrator"))
            {
                var currentUserId = User.Identity.GetUserId();
                var currentUserName = User.Identity.GetUserName();
                var contestTeachers = _db.ContestTeachers.Where(ct => ct.TeacherId == currentUserId);

                model = new ContestsIndexViewModel
                {
                    Contests =
                        _db.Contests.Include(c => c.ContestsType)
                            .Where(c => contestTeachers.Any(ct => ct.ContestId == c.Id))
                            .Include(c => c.Teacher)
                };
                return View(model);
            }

            model = new ContestsIndexViewModel
            {
                Contests = await _db.Contests.Include(c => c.ContestsType).Include(c => c.Teacher).ToListAsync()
            };

            return View(model);
        }

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Index(ContestsIndexViewModel model)
        {
            //ToDo: разобраться и доделать. Сейчас всегда возвращает null или model.Contests.Any() = false, этого не должно быть
            if (model != null && model.Contests != null && model.Contests.Any())
            {
                foreach (var contest in model.Contests)
                {
                    db.Entry(contest).State = EntityState.Modified;
                }
                await db.SaveChangesAsync();

                return View(model);
            }
            return RedirectToAction("Index");
        }*/

        public ActionResult Create()
        {
            var model = new ContestsCreateViewModel
            {
                ContestsTypes = new SelectList(_db.ContestsTypes, "Id", "Name")
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Create(ContestsCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await _db.Contests.AnyAsync(c => c.ContestsTypeId == model.ContestsTypeId && c.Name == model.Name))
                {
                    ModelState.AddModelError("", "Контест с таким именем и типом уже существует");
                }
                else
                {
                    var contest = new Contest
                    {
                        Id = Guid.NewGuid(),
                        ContestsTypeId = model.ContestsTypeId,
                        TeacherId = User.Identity.GetUserId(),
                        Name = model.Name,
                        IsActive = model.IsActive
                    };

                    var contestTeacher = new ContestTeacher
                    {
                        Id = Guid.NewGuid(),
                        ContestId = contest.Id,
                        TeacherId = contest.TeacherId
                    };

                    _db.Contests.Add(contest);
                    _db.ContestTeachers.Add(contestTeacher);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            model.ContestsTypes = new SelectList(_db.ContestsTypes, "Id", "Name");
            return View(model);
        }

        public async System.Threading.Tasks.Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var contest = await _db.Contests.FindAsync(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            if (contest.TeacherId != User.Identity.GetUserId() && !User.IsInRole("administrator") && !_db.ContestTeachers.Any(ct => ct.ContestId == contest.Id))
            {
                ViewBag.ErrorMessage = "Вы не имеете право редактировать этот контест";
                return View("Error");
            }
            var model = new ContestsEditViewModel
            {
                ContestId = contest.Id,
                ContestsTypeId = contest.ContestsTypeId,
                TeacherId = contest.TeacherId,
                Name = contest.Name,
                IsActive = contest.IsActive,
                ContestsTypes = new SelectList(_db.ContestsTypes, "Id", "Name")
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Edit(ContestsEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await _db.Contests.AnyAsync(c => c.ContestsTypeId == model.ContestsTypeId && c.Name == model.Name && c.Id != model.ContestId))
                {
                    ModelState.AddModelError("", "Контест с таким именем и типом уже существует");
                }
                else
                {
                    var teacherId = User.IsInRole("administrator") ? model.TeacherId : User.Identity.GetUserId();
                    var contest = new Contest
                    {
                        Id = model.ContestId,
                        ContestsTypeId = model.ContestsTypeId,
                        TeacherId = teacherId,
                        Name = model.Name,
                        IsActive = model.IsActive
                    };

                    _db.Entry(contest).State = EntityState.Modified;
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            model.ContestsTypes = new SelectList(_db.ContestsTypes, "Id", "Name");
            return View(model);
        }

        public async System.Threading.Tasks.Task<ActionResult> ExceptionsLogs(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var contest = await _db.Contests.FindAsync(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            if (contest.TeacherId != User.Identity.GetUserId() && !User.IsInRole("administrator") && !_db.ContestTeachers.Any(ct => ct.ContestId == contest.Id))
            {
                ViewBag.ErrorMessage = "Вы не имеете право смотреть логи исключений для данного контеста";
                return View("Error");
            }
            var model = new ContestsExceptionsLogsViewModel
            {
                ExceptionsLogs = _db.ExceptionsLogs.Include(x => x.User).Where(el => el.ContestId == contest.Id).OrderByDescending(el => el.CreatedDate),
                ContestName = contest.Name
            };
            return View(model);
        }

        public async System.Threading.Tasks.Task<ActionResult> DeleteExceptionsLog(Guid? contestId, Guid? id)
        {
            if (contestId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var contest = await _db.Contests.FindAsync(contestId);
            if (contest == null)
            {
                return HttpNotFound();
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var exceptionsLog = await _db.ExceptionsLogs.FindAsync(id);
            if (exceptionsLog == null)
            {
                return HttpNotFound();
            }
            _db.Entry(exceptionsLog).State = EntityState.Deleted;
            await _db.SaveChangesAsync();

            return RedirectToAction("ExceptionsLogs", new {id = contestId});
        }

        // GET: /Contests/Delete/5
        public async System.Threading.Tasks.Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var contest = await _db.Contests.FindAsync(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            if (contest.TeacherId != User.Identity.GetUserId() && !User.IsInRole("administrator") && !_db.ContestTeachers.Any(ct => ct.ContestId == contest.Id))
            {
                ViewBag.ErrorMessage = "Вы не имеете право удалять этот контест";
                return View("Error");
            }
            return View(contest);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> DeleteConfirmed(Guid id)
        {
            var contest = await _db.Contests.FindAsync(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            var tasks = await _db.Tasks.Where(t => t.ContestId == id).ToListAsync();
            foreach (var task in tasks)
            {
                _db.Tasks.Remove(task);
                DeleteTaskDescriptionFiles(task.Id);
            }

ContestMeter.Web.Site/Views/Contests/DevelopmentToolsList.cshtml
@using ContestMeter.Web.Site.Database.Entities
@using ContestMeter.Web.Site.Models
@model ContestsDevelopmentToolsListViewModel

<h2 class="alert alert-info">Компиляторы</h2>

<p>
    @Html.ActionLink("Добавить", "DevelopmentToolsCreate", "Contests", new { id = Model.ContestId }, null)
</p>
<table class="table">
    <tr>
        <th>Название</th>
        <th>Исполняемый файл</th>
        <th> Шаблон командной строки</th>
        <th></th>
    </tr>

@foreach (var item in Model.DevelopmentTools) {
    <tr class="alert alert-warning">
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompileCommand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CommandArgs)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "DevelopmentToolsEdit", "Contests", new { id=item.Id }, null) |
            @Html.ActionLink("Удалить", "DevelopmentToolsDelete", "Contests", new { id=item.Id }, null)
        </td>
    </tr>
}

</table>

ContestMeter.Web.Site/Views/Contests/Edit.cshtml
@using ContestMeter.Web.Site.Models
@model ContestsEditViewModel

@{
    ViewBag.Title = "Редактировать контест";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="alert alert-info">Редактировать контест <b>"@Model.Name"</b></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ContestId)
        @Html.HiddenFor(model => model.TeacherId)
        @if (TempData["Message"] != null && TempData["Message"].ToString() != "")
        {
            <br />
            <div class="col-md-12 alert alert-danger">@TempData["Message"]</div>
            <br />
        }
        
        <div class="alert alert-warning">
            <div class="form-group">
                @Html.Label("Тип контеста", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ContestsTypeId, Model.ContestsTypes, String.Empty)
                    @Html.ValidationMessageFor(model => model.ContestsTypeId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, "Название", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, "Активный?", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Сохранить" class="btn btn-default" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.Action("TeachersList", "Contests", new { id = Model.ContestId })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.Action("TasksList", "Contests", new { id = Model.ContestId })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-12">
                @Html.Action("DevelopmentToolsList", "Contests", new { id = Model.ContestId })
            </div>
        </div>
    </div>
}

<hr />
<div>
    @Html.ActionLink("Вернуться к списку контестов", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContestMeter.Web.Site/Views/Contests/TasksCreate.cshtml
@using ContestMeter.Web.Site.Models
@model ContestsTasksCreateViewModel

@{
    ViewBag.Title = "добавление задачи";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="alert alert-info">Добавить задачу</h2>


@using (Html.BeginForm("TasksCreate", "Contests", FormMethod.Post, new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal alert alert-warning">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ContestId)

        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ExecutableName, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.ExecutableName)
                    @Html.ValidationMessageFor(model => model.ExecutableName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CheckerName, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CheckerName)
                    @Html.ValidationMessageFor(model => model.CheckerName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TestsFolder, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.TestsFolder)
                    @Html.ValidationMessageFor(model => model.TestsFolder)
                </div>
            </div>
            
            
            @*ToDo: здесь сделать выпадающий список из остального*@

            <div class="form-group">
                @Html.LabelFor(model => model.TimeLimit, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.TimeLimit)
                    @Html.ValidationMessageFor(model => model.TimeLimit)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Weight, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Weight)
                    @Html.ValidationMessageFor(model => model.Weight)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaxSourceSize, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.MaxSourceSize)
                    @Html.ValidationMessageFor(model => model.MaxSourceSize)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaxMemorySize, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.MaxMemorySize)
                    @Html.ValidationMessageFor(model => model.MaxMemorySize)
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Загрузить файл с описанием задачи (в формате pdf)", new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    <input type="file" name="fileUpload" />
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Загрузить чекер к задаче", new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    <input type="file" id="checkerFile" name="checkerFile"/>
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Загрузить файлы тестов для задачи", new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    <input id="testsFiles" multiple="multiple" name="testsFiles" type="file" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">
                    <input type="submit" value="Добавить" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку задач", "Edit", "Contests", new { id = Model.ContestId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContestMeter.Web.Site/Views/Contests/TasksDelete.cshtml
@using ContestMeter.Web.Site.Models
@model ContestsTasksDeleteViewModel

@{
    ViewBag.Title = "Удаление задачи";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="alert alert-info">Удаление задачи</h2>

<h3 class="alert alert-warning">Вы действительно хотите удалить эту задачу?</h3>

<div class="col-md-12 alert alert-info">
    <dl>
        @Html.HiddenFor(model => model.ContestId)
        @Html.HiddenFor(model => model.TaskId)

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExecutableName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExecutableName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestsFolder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestsFolder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeLimit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeLimit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxSourceSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxSourceSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxMemorySize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxMemorySize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
    
    <br />
    <iframe class="col-md-12" src="@Model.TaskDescriptionFileName" height="400" style="border:0; margin-bottom: 25px"></iframe>
    <br />

    @using (Html.BeginForm("TasksDelete", "Contests", new { model = Model }, FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color col-lg-offset-4 col-md-8">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку задач", "Edit", new { id = Model.ContestId })
        </div>
    }
</div>

ContestMeter.Web.Site/Views/Contests/TasksEdit.cshtml
@using ContestMeter.Web.Site.Models
@model ContestsTasksEditViewModel
@{
    ViewBag.Title = "Редактирование задачи";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="alert alert-info">Редактирование задачи</h2>


@using (Html.BeginForm("TasksEdit", "Contests", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-12 alert alert-warning">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.TaskId)
        @Html.HiddenFor(model => model.ContestId)
        @Html.HiddenFor(model => model.Rating)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExecutableName, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ExecutableName)
                @Html.ValidationMessageFor(model => model.ExecutableName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckerName, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.CheckerName)
                @Html.ValidationMessageFor(model => model.CheckerName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestsFolder, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.TestsFolder)
                @Html.ValidationMessageFor(model => model.TestsFolder)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeLimit, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.TimeLimit)
                @Html.ValidationMessageFor(model => model.TimeLimit)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Weight)
                @Html.ValidationMessageFor(model => model.Weight)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxSourceSize, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.MaxSourceSize)
                @Html.ValidationMessageFor(model => model.MaxSourceSize)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxMemorySize, new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.MaxMemorySize)
                @Html.ValidationMessageFor(model => model.MaxMemorySize)
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Загрузить файл с описанием задачи (в формате pdf)", new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                <input type="file" name="fileUpload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку задач", "Edit", new { id = Model.ContestId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContestMeter.Web.Site/Views/Contests/TasksList.cshtml
@using ContestMeter.Web.Site.Database.Entities
@using ContestMeter.Web.Site.Models
@model ContestsTasksListViewModel

<h2 class="alert alert-info">Задачи</h2>

<p>
    @Html.ActionLink("Добавить", "TasksCreate", "Contests", new { id = Model.ContestId }, null)
</p>
<table class="table">
    <tr>
        <th>Название задачи</th>
        <th>Краткое название</th>
        <th>Проверяющая программа (с расширением)</th>
        <th>Папка с тестами</th>
        <th>Предел выполнения по времени (в сек.)</th>
        <th>Цена одного теста</th>
        <th>Максимальный размер исходника (в байтах). 0 - не ограничен</th>
        <th>Максимальный размер используемой памяти (в байтах). 0 - не ограничен</th>
        <th>Рейтинг задачи</th>
        <th></th>
    </tr>

    @foreach (var item in Model.Tasks)
    {
        <tr class="alert alert-warning">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExecutableName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TestsFolder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeLimit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxSourceSize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxMemorySize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "TasksEdit", "Contests", new { id = item.Id }, null) |
                @Html.ActionLink("Удалить", "TasksDelete", "Contests", new { id = item.Id }, null)
            </td>
        </tr>
    }
</table>

ContestMeter.Web.Site/Views/Contests/TeachersList.cshtml
@using ContestMeter.Web.Site.Database.Entities
@using ContestMeter.Web.Site.Models
@model ContestsTeachersListViewModel

<h2 class="alert alert-info">Преподаватели</h2>

<table class="table">
    <tr>
        <th>Логин</th>
        <th>Email</th>
        <th>Ip</th>
        <th>Фамилия</th>
        <th>Имя</th>
        <th>Отчество</th>
        <th></th>
    </tr>

    @foreach (var item in Model.ContestTeachers)
    {
        <tr class="alert alert-success">
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.ActionLink("Удалить", "DeleteTeachers", "Contests", new { contestId = Model.ContestId, id = item.Id }, null)
            </td>
        </tr>
    }

    @foreach (var item in Model.Teachers)
    {
        <tr class="alert alert-warning">
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.ActionLink("Добавить", "AddTeachers", "Contests", new { contestId = Model.ContestId, id = item.Id }, null)
            </td>
        </tr>
    }
</table>